### PR TITLE
Upgrade JavaScript Standard Style to v14

### PR DESCRIPTION
**Pull request by sonicdoe**

### CODE REVIEW

**Comment by sonicdoe** [comment]
Travis CI is failing because `standard` no longer supports Node.js v6.

Do you intend to continue support for this version or would you be open to a pull request dropping support? Node.js v6 is already [end-of-life](https://github.com/nodejs/Release#end-of-life-releases), by the way.

**Comment by DianaSuvorova** [comment]
@sonicdoe , thanks for the PR. Yes,  I think dropping node v6 is totally reasonable.  Please  free free to create a PR for this.

As for changes in this diff, is it possible to add an eslint  config and test that would enforce the style.

Thanks,
Diana

**Comment by sonicdoe** [comment]
> As for changes in this diff, is it possible to add an eslint config and test that would enforce the style.

This style is already enforced by [JavaScript Standard Style](https://standardjs.com) which runs on `pretest`:

https://github.com/tlvince/eslint-plugin-jasmine/blob/46041894ea7b2b249f3384dc1f0c034de0b0a421/package.json#L10

**Comment by DianaSuvorova** [comment]
> > As for changes in this diff, is it possible to add an eslint config and test that would enforce the style.
> 
> This style is already enforced by [JavaScript Standard Style](https://standardjs.com) which runs on `pretest`:
> 
> https://github.com/tlvince/eslint-plugin-jasmine/blob/46041894ea7b2b249f3384dc1f0c034de0b0a421/package.json#L10


uhm, I am confused, is `pretest` gets run on ci? If so how is this not failing on master.If not can we add it ?

**Comment by sonicdoe** [comment]
`pretest` runs as part of `yarn test` on Travis CI. It’s not failing on `master` because `standard` is still at v10.0.2 on that branch. If I would only update `standard` without fixing any errors, the build would fail as you can see with [this Travis CI build](https://travis-ci.org/sonicdoe/eslint-plugin-jasmine/builds/594155648).

**Pull request closed without merging**
