### PR TITLE
fix(named-spy): be more defensive to stop an exception if identifier …

### PR DESCRIPTION
**Pull request by lukeapage**
I get lots of exceptions on my code base enabling the rule. I didn't work out the exact thing causing it but I fixed it by being more defensive..

### CODE REVIEW

**Comment by burabure** [comment]
Could you show us a snippet of code where this happens? @lukeapage

**Comment by lukeapage** [comment]
I will look into when I have time - it'll take me about an hour to track down again, that might not happen for a couple of weeks.

**Comment by lukeapage** [comment]
```
mockFetchRequest = jasmine.createSpy('fetchRequest').and.callFake(requestUtils.statusAwareFetchRequest);
```

```
Node {
  type: 'CallExpression',
  start: 874,
  end: 907,
  loc:
   SourceLocation {
     start: Position { line: 18, column: 27 },
     end: Position { line: 18, column: 60 } },
  range: [ 874, 907 ],
  callee:
   Node {
     type: 'MemberExpression',
     start: 874,
     end: 891,
     loc: SourceLocation { start: [Object], end: [Object] },
     range: [ 874, 891 ],
     object:
      Node {
        type: 'Identifier',
        start: 874,
        end: 881,
        loc: [Object],
        range: [Object],
        name: 'jasmine' },
     property:
      Node {
        type: 'Identifier',
        start: 882,
        end: 891,
        loc: [Object],
        range: [Object],
        name: 'createSpy' },
     computed: false },
  arguments:
   [ Node {
       type: 'Literal',
       start: 892,
       end: 906,
       loc: [Object],
       range: [Object],
       value: 'fetchRequest',
       raw: '\'fetchRequest\'' } ],
  parent:
   Node {
     type: 'MemberExpression',
     start: 874,
     end: 911,
     loc: SourceLocation { start: [Object], end: [Object] },
     range: [ 874, 911 ],
     object: [Circular],
     property:
      Node {
        type: 'Identifier',
        start: 908,
        end: 911,
        loc: [Object],
        range: [Object],
        name: 'and' },
     computed: false,
     parent:
      Node {
        type: 'MemberExpression',
        start: 874,
        end: 920,
        loc: [Object],
        range: [Object],
        object: [Circular],
        property: [Object],
        computed: false,
        parent: [Object] } } }
```

So the parent is a member expression so identifier is never set.

To be most effective I guess the rule should go up the parents till it becomes a assignment or a declaration or a statement..

**Comment by burabure** [comment]
@lukeapage could you make those changes and amend the PR?

ps: look here on how to work with parents in an efficent manner https://github.com/tlvince/eslint-plugin-jasmine/blob/master/lib/rules/no-global-setup.js

**Pull request closed without merging**
